//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1591

// Generated from: steammessages_remoteclient.proto
// Note: requires additional types generated from: steammessages_base.proto
// Note: requires additional types generated from: steammessages_remoteclient_discovery.proto
using steammessages_remoteclient_discovery;
namespace steammessages_remoteclient
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteClientAppStatus")]
  public partial class CMsgRemoteClientAppStatus : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteClientAppStatus() {}
    
    private readonly global::System.Collections.Generic.List<CMsgRemoteClientAppStatus.AppStatus> _status_updates = new global::System.Collections.Generic.List<CMsgRemoteClientAppStatus.AppStatus>();
    [global::ProtoBuf.ProtoMember(1, Name=@"status_updates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CMsgRemoteClientAppStatus.AppStatus> status_updates
    {
      get { return _status_updates; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AppUpdateInfo")]
  public partial class AppUpdateInfo : global::ProtoBuf.IExtensible
  {
    public AppUpdateInfo() {}
    

    private uint _time_update_start = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"time_update_start", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time_update_start
    {
      get { return _time_update_start; }
      set { _time_update_start = value; }
    }

    private ulong _bytes_to_download = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bytes_to_download", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong bytes_to_download
    {
      get { return _bytes_to_download; }
      set { _bytes_to_download = value; }
    }

    private ulong _bytes_downloaded = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bytes_downloaded", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong bytes_downloaded
    {
      get { return _bytes_downloaded; }
      set { _bytes_downloaded = value; }
    }

    private ulong _bytes_to_process = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bytes_to_process", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong bytes_to_process
    {
      get { return _bytes_to_process; }
      set { _bytes_to_process = value; }
    }

    private ulong _bytes_processed = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"bytes_processed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong bytes_processed
    {
      get { return _bytes_processed; }
      set { _bytes_processed = value; }
    }

    private int _estimated_seconds_remaining = (int)-1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"estimated_seconds_remaining", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int estimated_seconds_remaining
    {
      get { return _estimated_seconds_remaining; }
      set { _estimated_seconds_remaining = value; }
    }

    private int _update_result = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"update_result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int update_result
    {
      get { return _update_result; }
      set { _update_result = value; }
    }

    private uint _update_state = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"update_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint update_state
    {
      get { return _update_state; }
      set { _update_state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShortcutInfo")]
  public partial class ShortcutInfo : global::ProtoBuf.IExtensible
  {
    public ShortcutInfo() {}
    

    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _icon = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _categories = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"categories", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> categories
    {
      get { return _categories; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AppStatus")]
  public partial class AppStatus : global::ProtoBuf.IExtensible
  {
    public AppStatus() {}
    

    private uint _app_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"app_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint app_id
    {
      get { return _app_id; }
      set { _app_id = value; }
    }

    private uint _app_state = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"app_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint app_state
    {
      get { return _app_state; }
      set { _app_state = value; }
    }

    private CMsgRemoteClientAppStatus.AppUpdateInfo _update_info = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"update_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CMsgRemoteClientAppStatus.AppUpdateInfo update_info
    {
      get { return _update_info; }
      set { _update_info = value; }
    }

    private CMsgRemoteClientAppStatus.ShortcutInfo _shortcut_info = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"shortcut_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CMsgRemoteClientAppStatus.ShortcutInfo shortcut_info
    {
      get { return _shortcut_info; }
      set { _shortcut_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteClientAuth")]
  public partial class CMsgRemoteClientAuth : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteClientAuth() {}
    

    private ulong _client_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"client_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong client_id
    {
      get { return _client_id; }
      set { _client_id = value; }
    }

    private CMsgRemoteClientBroadcastStatus _status = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CMsgRemoteClientBroadcastStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteClientAuthResponse")]
  public partial class CMsgRemoteClientAuthResponse : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteClientAuthResponse() {}
    

    private int _eresult = (int)2;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"eresult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)2)]
    public int eresult
    {
      get { return _eresult; }
      set { _eresult = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteClientStartStream")]
  public partial class CMsgRemoteClientStartStream : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteClientStartStream() {}
    

    private uint _app_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"app_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint app_id
    {
      get { return _app_id; }
      set { _app_id = value; }
    }

    private int _environment = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"environment", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int environment
    {
      get { return _environment; }
      set { _environment = value; }
    }

    private int _gamepad_count = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gamepad_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gamepad_count
    {
      get { return _gamepad_count; }
      set { _gamepad_count = value; }
    }

    private int _launch_option = (int)-1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"launch_option", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int launch_option
    {
      get { return _launch_option; }
      set { _launch_option = value; }
    }

    private bool _lock_parental_lock = (bool)false;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"lock_parental_lock", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool lock_parental_lock
    {
      get { return _lock_parental_lock; }
      set { _lock_parental_lock = value; }
    }

    private string _unlock_parental_lock = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"unlock_parental_lock", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string unlock_parental_lock
    {
      get { return _unlock_parental_lock; }
      set { _unlock_parental_lock = value; }
    }

    private int _maximum_resolution_x = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"maximum_resolution_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maximum_resolution_x
    {
      get { return _maximum_resolution_x; }
      set { _maximum_resolution_x = value; }
    }

    private int _maximum_resolution_y = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"maximum_resolution_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maximum_resolution_y
    {
      get { return _maximum_resolution_y; }
      set { _maximum_resolution_y = value; }
    }
    private readonly global::System.Collections.Generic.List<CMsgRemoteClientStartStream.ReservedGamepad> _gamepads = new global::System.Collections.Generic.List<CMsgRemoteClientStartStream.ReservedGamepad>();
    [global::ProtoBuf.ProtoMember(9, Name=@"gamepads", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CMsgRemoteClientStartStream.ReservedGamepad> gamepads
    {
      get { return _gamepads; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReservedGamepad")]
  public partial class ReservedGamepad : global::ProtoBuf.IExtensible
  {
    public ReservedGamepad() {}
    

    private uint _controller_type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"controller_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint controller_type
    {
      get { return _controller_type; }
      set { _controller_type = value; }
    }

    private uint _controller_subtype = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"controller_subtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint controller_subtype
    {
      get { return _controller_subtype; }
      set { _controller_subtype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteClientStartStreamResponse")]
  public partial class CMsgRemoteClientStartStreamResponse : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteClientStartStreamResponse() {}
    

    private int _e_launch_result = (int)2;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"e_launch_result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)2)]
    public int e_launch_result
    {
      get { return _e_launch_result; }
      set { _e_launch_result = value; }
    }

    private uint _stream_port = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stream_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint stream_port
    {
      get { return _stream_port; }
      set { _stream_port = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _launch_options = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"launch_options", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> launch_options
    {
      get { return _launch_options; }
    }
  

    private byte[] _auth_token = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"auth_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] auth_token
    {
      get { return _auth_token; }
      set { _auth_token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteClientPing")]
  public partial class CMsgRemoteClientPing : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteClientPing() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteClientPingResponse")]
  public partial class CMsgRemoteClientPingResponse : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteClientPingResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteClientAcceptEULA")]
  public partial class CMsgRemoteClientAcceptEULA : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteClientAcceptEULA() {}
    
    private readonly global::System.Collections.Generic.List<uint> _app_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"app_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> app_id
    {
      get { return _app_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteClientGetControllerConfig")]
  public partial class CMsgRemoteClientGetControllerConfig : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteClientGetControllerConfig() {}
    

    private uint _app_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"app_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint app_id
    {
      get { return _app_id; }
      set { _app_id = value; }
    }

    private int _window_type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"window_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int window_type
    {
      get { return _window_type; }
      set { _window_type = value; }
    }

    private uint _controller_index = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"controller_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint controller_index
    {
      get { return _controller_index; }
      set { _controller_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteClientGetControllerConfigResponse")]
  public partial class CMsgRemoteClientGetControllerConfigResponse : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteClientGetControllerConfigResponse() {}
    

    private int _eresult = (int)2;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"eresult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)2)]
    public int eresult
    {
      get { return _eresult; }
      set { _eresult = value; }
    }

    private byte[] _config_vdf = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"config_vdf", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] config_vdf
    {
      get { return _config_vdf; }
      set { _config_vdf = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteClientStreamingEnabled")]
  public partial class CMsgRemoteClientStreamingEnabled : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteClientStreamingEnabled() {}
    
    private bool _enabled;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"enabled", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool enabled
    {
      get { return _enabled; }
      set { _enabled = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
#pragma warning restore 1591
