//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1591

// Generated from: steammessages_remoteclient_discovery.proto
namespace steammessages_remoteclient_discovery
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteClientBroadcastHeader")]
  public partial class CMsgRemoteClientBroadcastHeader : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteClientBroadcastHeader() {}
    

    private ulong _client_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"client_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong client_id
    {
      get { return _client_id; }
      set { _client_id = value; }
    }

    private ERemoteClientBroadcastMsg _msg_type = ERemoteClientBroadcastMsg.k_ERemoteClientBroadcastMsgDiscovery;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"msg_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ERemoteClientBroadcastMsg.k_ERemoteClientBroadcastMsgDiscovery)]
    public ERemoteClientBroadcastMsg msg_type
    {
      get { return _msg_type; }
      set { _msg_type = value; }
    }

    private ulong _instance_id = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"instance_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong instance_id
    {
      get { return _instance_id; }
      set { _instance_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteClientBroadcastStatus")]
  public partial class CMsgRemoteClientBroadcastStatus : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteClientBroadcastStatus() {}
    

    private int _version = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }

    private int _min_version = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"min_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int min_version
    {
      get { return _min_version; }
      set { _min_version = value; }
    }

    private uint _connect_port = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"connect_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint connect_port
    {
      get { return _connect_port; }
      set { _connect_port = value; }
    }

    private string _hostname = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hostname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hostname
    {
      get { return _hostname; }
      set { _hostname = value; }
    }

    private uint _enabled_services = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"enabled_services", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint enabled_services
    {
      get { return _enabled_services; }
      set { _enabled_services = value; }
    }

    private int _ostype = (int)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ostype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int ostype
    {
      get { return _ostype; }
      set { _ostype = value; }
    }

    private bool _is64bit = (bool)false;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"is64bit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool is64bit
    {
      get { return _is64bit; }
      set { _is64bit = value; }
    }
    private readonly global::System.Collections.Generic.List<CMsgRemoteClientBroadcastStatus.User> _users = new global::System.Collections.Generic.List<CMsgRemoteClientBroadcastStatus.User>();
    [global::ProtoBuf.ProtoMember(9, Name=@"users", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CMsgRemoteClientBroadcastStatus.User> users
    {
      get { return _users; }
    }
  

    private uint _remote_control_port = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"remote_control_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint remote_control_port
    {
      get { return _remote_control_port; }
      set { _remote_control_port = value; }
    }

    private int _euniverse = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"euniverse", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int euniverse
    {
      get { return _euniverse; }
      set { _euniverse = value; }
    }

    private uint _timestamp = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"User")]
  public partial class User : global::ProtoBuf.IExtensible
  {
    public User() {}
    

    private ulong _steamid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"steamid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong steamid
    {
      get { return _steamid; }
      set { _steamid = value; }
    }

    private uint _auth_key_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"auth_key_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint auth_key_id
    {
      get { return _auth_key_id; }
      set { _auth_key_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteClientBroadcastDiscovery")]
  public partial class CMsgRemoteClientBroadcastDiscovery : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteClientBroadcastDiscovery() {}
    

    private uint _seq_num = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"seq_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint seq_num
    {
      get { return _seq_num; }
      set { _seq_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteDeviceAuthorizationRequest")]
  public partial class CMsgRemoteDeviceAuthorizationRequest : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteDeviceAuthorizationRequest() {}
    
    private byte[] _device_token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"device_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] device_token
    {
      get { return _device_token; }
      set { _device_token = value; }
    }

    private string _device_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"device_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string device_name
    {
      get { return _device_name; }
      set { _device_name = value; }
    }
    private byte[] _encrypted_request;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"encrypted_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] encrypted_request
    {
      get { return _encrypted_request; }
      set { _encrypted_request = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CKeyEscrow_Ticket")]
  public partial class CKeyEscrow_Ticket : global::ProtoBuf.IExtensible
  {
    public CKeyEscrow_Ticket() {}
    

    private byte[] _password = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] password
    {
      get { return _password; }
      set { _password = value; }
    }

    private ulong _identifier = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"identifier", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong identifier
    {
      get { return _identifier; }
      set { _identifier = value; }
    }

    private byte[] _payload = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"payload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] payload
    {
      get { return _payload; }
      set { _payload = value; }
    }

    private uint _timestamp = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }

    private CMsgRemoteDeviceAuthorizationRequest.EKeyEscrowUsage _usage = CMsgRemoteDeviceAuthorizationRequest.EKeyEscrowUsage.k_EKeyEscrowUsageStreamingDevice;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"usage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(CMsgRemoteDeviceAuthorizationRequest.EKeyEscrowUsage.k_EKeyEscrowUsageStreamingDevice)]
    public CMsgRemoteDeviceAuthorizationRequest.EKeyEscrowUsage usage
    {
      get { return _usage; }
      set { _usage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EKeyEscrowUsage", EnumPassthru=true)]
    public enum EKeyEscrowUsage
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EKeyEscrowUsageStreamingDevice", Value=0)]
      k_EKeyEscrowUsageStreamingDevice = 0
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteDeviceAuthorizationResponse")]
  public partial class CMsgRemoteDeviceAuthorizationResponse : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteDeviceAuthorizationResponse() {}
    
    private ERemoteDeviceAuthorizationResult _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ERemoteDeviceAuthorizationResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteDeviceStreamingRequest")]
  public partial class CMsgRemoteDeviceStreamingRequest : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteDeviceStreamingRequest() {}
    
    private uint _request_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"request_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint request_id
    {
      get { return _request_id; }
      set { _request_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteDeviceStreamingResponse")]
  public partial class CMsgRemoteDeviceStreamingResponse : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteDeviceStreamingResponse() {}
    
    private uint _request_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"request_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint request_id
    {
      get { return _request_id; }
      set { _request_id = value; }
    }
    private ERemoteDeviceStreamingResult _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ERemoteDeviceStreamingResult result
    {
      get { return _result; }
      set { _result = value; }
    }

    private uint _port = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }

    private byte[] _encrypted_session_key = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"encrypted_session_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] encrypted_session_key
    {
      get { return _encrypted_session_key; }
      set { _encrypted_session_key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteDeviceProofRequest")]
  public partial class CMsgRemoteDeviceProofRequest : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteDeviceProofRequest() {}
    
    private byte[] _challenge;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"challenge", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] challenge
    {
      get { return _challenge; }
      set { _challenge = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRemoteDeviceProofResponse")]
  public partial class CMsgRemoteDeviceProofResponse : global::ProtoBuf.IExtensible
  {
    public CMsgRemoteDeviceProofResponse() {}
    
    private byte[] _response;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] response
    {
      get { return _response; }
      set { _response = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ERemoteClientBroadcastMsg", EnumPassthru=true)]
    public enum ERemoteClientBroadcastMsg
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteClientBroadcastMsgDiscovery", Value=0)]
      k_ERemoteClientBroadcastMsgDiscovery = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteClientBroadcastMsgStatus", Value=1)]
      k_ERemoteClientBroadcastMsgStatus = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteClientBroadcastMsgOffline", Value=2)]
      k_ERemoteClientBroadcastMsgOffline = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceAuthorizationRequest", Value=3)]
      k_ERemoteDeviceAuthorizationRequest = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceAuthorizationResponse", Value=4)]
      k_ERemoteDeviceAuthorizationResponse = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceStreamingRequest", Value=5)]
      k_ERemoteDeviceStreamingRequest = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceStreamingResponse", Value=6)]
      k_ERemoteDeviceStreamingResponse = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceProofRequest", Value=7)]
      k_ERemoteDeviceProofRequest = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceProofResponse", Value=8)]
      k_ERemoteDeviceProofResponse = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ERemoteClientService", EnumPassthru=true)]
    public enum ERemoteClientService
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteClientServiceNone", Value=0)]
      k_ERemoteClientServiceNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteClientServiceRemoteControl", Value=1)]
      k_ERemoteClientServiceRemoteControl = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteClientServiceGameStreaming", Value=2)]
      k_ERemoteClientServiceGameStreaming = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ERemoteDeviceAuthorizationResult", EnumPassthru=true)]
    public enum ERemoteDeviceAuthorizationResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceAuthorizationSuccess", Value=0)]
      k_ERemoteDeviceAuthorizationSuccess = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceAuthorizationDenied", Value=1)]
      k_ERemoteDeviceAuthorizationDenied = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceAuthorizationNotLoggedIn", Value=2)]
      k_ERemoteDeviceAuthorizationNotLoggedIn = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceAuthorizationOffline", Value=3)]
      k_ERemoteDeviceAuthorizationOffline = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceAuthorizationBusy", Value=4)]
      k_ERemoteDeviceAuthorizationBusy = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceAuthorizationInProgress", Value=5)]
      k_ERemoteDeviceAuthorizationInProgress = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceAuthorizationTimedOut", Value=6)]
      k_ERemoteDeviceAuthorizationTimedOut = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceAuthorizationFailed", Value=7)]
      k_ERemoteDeviceAuthorizationFailed = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ERemoteDeviceStreamingResult", EnumPassthru=true)]
    public enum ERemoteDeviceStreamingResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceStreamingSuccess", Value=0)]
      k_ERemoteDeviceStreamingSuccess = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceStreamingUnauthorized", Value=1)]
      k_ERemoteDeviceStreamingUnauthorized = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceStreamingScreenLocked", Value=2)]
      k_ERemoteDeviceStreamingScreenLocked = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceStreamingFailed", Value=3)]
      k_ERemoteDeviceStreamingFailed = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceStreamingBusy", Value=4)]
      k_ERemoteDeviceStreamingBusy = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_ERemoteDeviceStreamingInProgress", Value=5)]
      k_ERemoteDeviceStreamingInProgress = 5
    }
  
}
#pragma warning restore 1591
