//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1591

// Generated from: stream.proto
namespace stream
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CDiscoveryRequest")]
  public partial class CDiscoveryRequest : global::ProtoBuf.IExtensible
  {
    public CDiscoveryRequest() {}
    

    private byte[] _token = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] token
    {
      get { return _token; }
      set { _token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CDiscoveryResponse")]
  public partial class CDiscoveryResponse : global::ProtoBuf.IExtensible
  {
    public CDiscoveryResponse() {}
    

    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CAuthenticationRequestMsg")]
  public partial class CAuthenticationRequestMsg : global::ProtoBuf.IExtensible
  {
    public CAuthenticationRequestMsg() {}
    

    private byte[] _token = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] token
    {
      get { return _token; }
      set { _token = value; }
    }

    private EStreamVersion _version = EStreamVersion.k_EStreamVersionNone;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(EStreamVersion.k_EStreamVersionNone)]
    public EStreamVersion version
    {
      get { return _version; }
      set { _version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CAuthenticationResponseMsg")]
  public partial class CAuthenticationResponseMsg : global::ProtoBuf.IExtensible
  {
    public CAuthenticationResponseMsg() {}
    

    private CAuthenticationResponseMsg.AuthenticationResult _result = CAuthenticationResponseMsg.AuthenticationResult.SUCCEEDED;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(CAuthenticationResponseMsg.AuthenticationResult.SUCCEEDED)]
    public CAuthenticationResponseMsg.AuthenticationResult result
    {
      get { return _result; }
      set { _result = value; }
    }

    private EStreamVersion _version = EStreamVersion.k_EStreamVersionNone;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(EStreamVersion.k_EStreamVersionNone)]
    public EStreamVersion version
    {
      get { return _version; }
      set { _version = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"AuthenticationResult", EnumPassthru=true)]
    public enum AuthenticationResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCEEDED", Value=0)]
      SUCCEEDED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAILED", Value=1)]
      FAILED = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CStreamVideoMode")]
  public partial class CStreamVideoMode : global::ProtoBuf.IExtensible
  {
    public CStreamVideoMode() {}
    
    private uint _width;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint width
    {
      get { return _width; }
      set { _width = value; }
    }
    private uint _height;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint height
    {
      get { return _height; }
      set { _height = value; }
    }

    private uint _refresh_rate = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"refresh_rate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint refresh_rate
    {
      get { return _refresh_rate; }
      set { _refresh_rate = value; }
    }

    private uint _refresh_rate_numerator = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"refresh_rate_numerator", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint refresh_rate_numerator
    {
      get { return _refresh_rate_numerator; }
      set { _refresh_rate_numerator = value; }
    }

    private uint _refresh_rate_denominator = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"refresh_rate_denominator", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint refresh_rate_denominator
    {
      get { return _refresh_rate_denominator; }
      set { _refresh_rate_denominator = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CNegotiatedConfig")]
  public partial class CNegotiatedConfig : global::ProtoBuf.IExtensible
  {
    public CNegotiatedConfig() {}
    

    private bool _reliable_data = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reliable_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool reliable_data
    {
      get { return _reliable_data; }
      set { _reliable_data = value; }
    }

    private EStreamAudioCodec _selected_audio_codec = EStreamAudioCodec.k_EStreamAudioCodecNone;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"selected_audio_codec", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(EStreamAudioCodec.k_EStreamAudioCodecNone)]
    public EStreamAudioCodec selected_audio_codec
    {
      get { return _selected_audio_codec; }
      set { _selected_audio_codec = value; }
    }

    private EStreamVideoCodec _selected_video_codec = EStreamVideoCodec.k_EStreamVideoCodecNone;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"selected_video_codec", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(EStreamVideoCodec.k_EStreamVideoCodecNone)]
    public EStreamVideoCodec selected_video_codec
    {
      get { return _selected_video_codec; }
      set { _selected_video_codec = value; }
    }
    private readonly global::System.Collections.Generic.List<CStreamVideoMode> _available_video_modes = new global::System.Collections.Generic.List<CStreamVideoMode>();
    [global::ProtoBuf.ProtoMember(4, Name=@"available_video_modes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CStreamVideoMode> available_video_modes
    {
      get { return _available_video_modes; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CNegotiationInitMsg")]
  public partial class CNegotiationInitMsg : global::ProtoBuf.IExtensible
  {
    public CNegotiationInitMsg() {}
    

    private bool _reliable_data = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reliable_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool reliable_data
    {
      get { return _reliable_data; }
      set { _reliable_data = value; }
    }
    private readonly global::System.Collections.Generic.List<EStreamAudioCodec> _supported_audio_codecs = new global::System.Collections.Generic.List<EStreamAudioCodec>();
    [global::ProtoBuf.ProtoMember(2, Name=@"supported_audio_codecs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<EStreamAudioCodec> supported_audio_codecs
    {
      get { return _supported_audio_codecs; }
    }
  
    private readonly global::System.Collections.Generic.List<EStreamVideoCodec> _supported_video_codecs = new global::System.Collections.Generic.List<EStreamVideoCodec>();
    [global::ProtoBuf.ProtoMember(3, Name=@"supported_video_codecs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<EStreamVideoCodec> supported_video_codecs
    {
      get { return _supported_video_codecs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CNegotiationSetConfigMsg")]
  public partial class CNegotiationSetConfigMsg : global::ProtoBuf.IExtensible
  {
    public CNegotiationSetConfigMsg() {}
    
    private CNegotiatedConfig _config;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"config", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CNegotiatedConfig config
    {
      get { return _config; }
      set { _config = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CNegotiationCompleteMsg")]
  public partial class CNegotiationCompleteMsg : global::ProtoBuf.IExtensible
  {
    public CNegotiationCompleteMsg() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CStartAudioDataMsg")]
  public partial class CStartAudioDataMsg : global::ProtoBuf.IExtensible
  {
    public CStartAudioDataMsg() {}
    
    private uint _channel;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"channel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint channel
    {
      get { return _channel; }
      set { _channel = value; }
    }

    private EStreamAudioCodec _codec = EStreamAudioCodec.k_EStreamAudioCodecNone;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"codec", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(EStreamAudioCodec.k_EStreamAudioCodecNone)]
    public EStreamAudioCodec codec
    {
      get { return _codec; }
      set { _codec = value; }
    }

    private byte[] _codec_data = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"codec_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] codec_data
    {
      get { return _codec_data; }
      set { _codec_data = value; }
    }

    private uint _frequency = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"frequency", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint frequency
    {
      get { return _frequency; }
      set { _frequency = value; }
    }

    private uint _channels = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"channels", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint channels
    {
      get { return _channels; }
      set { _channels = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CStopAudioDataMsg")]
  public partial class CStopAudioDataMsg : global::ProtoBuf.IExtensible
  {
    public CStopAudioDataMsg() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CStartVideoDataMsg")]
  public partial class CStartVideoDataMsg : global::ProtoBuf.IExtensible
  {
    public CStartVideoDataMsg() {}
    
    private uint _channel;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint channel
    {
      get { return _channel; }
      set { _channel = value; }
    }

    private EStreamVideoCodec _codec = EStreamVideoCodec.k_EStreamVideoCodecNone;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"codec", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(EStreamVideoCodec.k_EStreamVideoCodecNone)]
    public EStreamVideoCodec codec
    {
      get { return _codec; }
      set { _codec = value; }
    }

    private byte[] _codec_data = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"codec_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] codec_data
    {
      get { return _codec_data; }
      set { _codec_data = value; }
    }

    private uint _width = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint width
    {
      get { return _width; }
      set { _width = value; }
    }

    private uint _height = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint height
    {
      get { return _height; }
      set { _height = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CStopVideoDataMsg")]
  public partial class CStopVideoDataMsg : global::ProtoBuf.IExtensible
  {
    public CStopVideoDataMsg() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CInputLatencyTestMsg")]
  public partial class CInputLatencyTestMsg : global::ProtoBuf.IExtensible
  {
    public CInputLatencyTestMsg() {}
    
    private uint _input_mark;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"input_mark", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint input_mark
    {
      get { return _input_mark; }
      set { _input_mark = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CInputMouseMotionMsg")]
  public partial class CInputMouseMotionMsg : global::ProtoBuf.IExtensible
  {
    public CInputMouseMotionMsg() {}
    

    private uint _input_mark = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"input_mark", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint input_mark
    {
      get { return _input_mark; }
      set { _input_mark = value; }
    }

    private float _x_normalized = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"x_normalized", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x_normalized
    {
      get { return _x_normalized; }
      set { _x_normalized = value; }
    }

    private float _y_normalized = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"y_normalized", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y_normalized
    {
      get { return _y_normalized; }
      set { _y_normalized = value; }
    }

    private int _dx = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dx
    {
      get { return _dx; }
      set { _dx = value; }
    }

    private int _dy = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"dy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dy
    {
      get { return _dy; }
      set { _dy = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CInputMouseWheelMsg")]
  public partial class CInputMouseWheelMsg : global::ProtoBuf.IExtensible
  {
    public CInputMouseWheelMsg() {}
    

    private uint _input_mark = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"input_mark", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint input_mark
    {
      get { return _input_mark; }
      set { _input_mark = value; }
    }
    private EStreamMouseWheelDirection _direction;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EStreamMouseWheelDirection direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CInputMouseDownMsg")]
  public partial class CInputMouseDownMsg : global::ProtoBuf.IExtensible
  {
    public CInputMouseDownMsg() {}
    

    private uint _input_mark = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"input_mark", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint input_mark
    {
      get { return _input_mark; }
      set { _input_mark = value; }
    }
    private EStreamMouseButton _button;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"button", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EStreamMouseButton button
    {
      get { return _button; }
      set { _button = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CInputMouseUpMsg")]
  public partial class CInputMouseUpMsg : global::ProtoBuf.IExtensible
  {
    public CInputMouseUpMsg() {}
    

    private uint _input_mark = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"input_mark", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint input_mark
    {
      get { return _input_mark; }
      set { _input_mark = value; }
    }
    private EStreamMouseButton _button;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"button", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EStreamMouseButton button
    {
      get { return _button; }
      set { _button = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CInputKeyDownMsg")]
  public partial class CInputKeyDownMsg : global::ProtoBuf.IExtensible
  {
    public CInputKeyDownMsg() {}
    

    private uint _input_mark = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"input_mark", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint input_mark
    {
      get { return _input_mark; }
      set { _input_mark = value; }
    }
    private uint _scancode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"scancode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint scancode
    {
      get { return _scancode; }
      set { _scancode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CInputKeyUpMsg")]
  public partial class CInputKeyUpMsg : global::ProtoBuf.IExtensible
  {
    public CInputKeyUpMsg() {}
    

    private uint _input_mark = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"input_mark", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint input_mark
    {
      get { return _input_mark; }
      set { _input_mark = value; }
    }
    private uint _scancode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"scancode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint scancode
    {
      get { return _scancode; }
      set { _scancode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CInputGamepadAttachedMsg")]
  public partial class CInputGamepadAttachedMsg : global::ProtoBuf.IExtensible
  {
    public CInputGamepadAttachedMsg() {}
    
    private int _controller_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"controller_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int controller_id
    {
      get { return _controller_id; }
      set { _controller_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CInputGamepadEventMsg")]
  public partial class CInputGamepadEventMsg : global::ProtoBuf.IExtensible
  {
    public CInputGamepadEventMsg() {}
    

    private uint _input_mark = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"input_mark", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint input_mark
    {
      get { return _input_mark; }
      set { _input_mark = value; }
    }
    private int _controller_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"controller_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int controller_id
    {
      get { return _controller_id; }
      set { _controller_id = value; }
    }
    private EStreamGamepadInputType _input;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"input", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EStreamGamepadInputType input
    {
      get { return _input; }
      set { _input = value; }
    }
    private float _value;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CInputGamepadDetachedMsg")]
  public partial class CInputGamepadDetachedMsg : global::ProtoBuf.IExtensible
  {
    public CInputGamepadDetachedMsg() {}
    
    private int _controller_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"controller_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int controller_id
    {
      get { return _controller_id; }
      set { _controller_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CGamepadRumbleMsg")]
  public partial class CGamepadRumbleMsg : global::ProtoBuf.IExtensible
  {
    public CGamepadRumbleMsg() {}
    
    private int _controller_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"controller_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int controller_id
    {
      get { return _controller_id; }
      set { _controller_id = value; }
    }

    private int _left_motor_speed = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"left_motor_speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int left_motor_speed
    {
      get { return _left_motor_speed; }
      set { _left_motor_speed = value; }
    }

    private int _right_motor_speed = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"right_motor_speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int right_motor_speed
    {
      get { return _right_motor_speed; }
      set { _right_motor_speed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSetTitleMsg")]
  public partial class CSetTitleMsg : global::ProtoBuf.IExtensible
  {
    public CSetTitleMsg() {}
    

    private string _text = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSetIconMsg")]
  public partial class CSetIconMsg : global::ProtoBuf.IExtensible
  {
    public CSetIconMsg() {}
    

    private int _width = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int width
    {
      get { return _width; }
      set { _width = value; }
    }

    private int _height = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int height
    {
      get { return _height; }
      set { _height = value; }
    }

    private byte[] _image = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"image", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] image
    {
      get { return _image; }
      set { _image = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CShowCursorMsg")]
  public partial class CShowCursorMsg : global::ProtoBuf.IExtensible
  {
    public CShowCursorMsg() {}
    

    private float _x_normalized = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x_normalized", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x_normalized
    {
      get { return _x_normalized; }
      set { _x_normalized = value; }
    }

    private float _y_normalized = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y_normalized", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y_normalized
    {
      get { return _y_normalized; }
      set { _y_normalized = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHideCursorMsg")]
  public partial class CHideCursorMsg : global::ProtoBuf.IExtensible
  {
    public CHideCursorMsg() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSetCursorMsg")]
  public partial class CSetCursorMsg : global::ProtoBuf.IExtensible
  {
    public CSetCursorMsg() {}
    
    private ulong _cursor_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cursor_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong cursor_id
    {
      get { return _cursor_id; }
      set { _cursor_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CGetCursorImageMsg")]
  public partial class CGetCursorImageMsg : global::ProtoBuf.IExtensible
  {
    public CGetCursorImageMsg() {}
    
    private ulong _cursor_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cursor_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong cursor_id
    {
      get { return _cursor_id; }
      set { _cursor_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSetCursorImageMsg")]
  public partial class CSetCursorImageMsg : global::ProtoBuf.IExtensible
  {
    public CSetCursorImageMsg() {}
    
    private ulong _cursor_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cursor_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong cursor_id
    {
      get { return _cursor_id; }
      set { _cursor_id = value; }
    }

    private int _width = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int width
    {
      get { return _width; }
      set { _width = value; }
    }

    private int _height = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int height
    {
      get { return _height; }
      set { _height = value; }
    }

    private int _hot_x = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hot_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hot_x
    {
      get { return _hot_x; }
      set { _hot_x = value; }
    }

    private int _hot_y = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"hot_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hot_y
    {
      get { return _hot_y; }
      set { _hot_y = value; }
    }

    private byte[] _image = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"image", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] image
    {
      get { return _image; }
      set { _image = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSystemInfoMsg")]
  public partial class CSystemInfoMsg : global::ProtoBuf.IExtensible
  {
    public CSystemInfoMsg() {}
    

    private string _info = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CVideoDecoderInfoMsg")]
  public partial class CVideoDecoderInfoMsg : global::ProtoBuf.IExtensible
  {
    public CVideoDecoderInfoMsg() {}
    

    private string _info = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CQuitRequest")]
  public partial class CQuitRequest : global::ProtoBuf.IExtensible
  {
    public CQuitRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CDeleteCursorMsg")]
  public partial class CDeleteCursorMsg : global::ProtoBuf.IExtensible
  {
    public CDeleteCursorMsg() {}
    
    private ulong _cursor_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cursor_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong cursor_id
    {
      get { return _cursor_id; }
      set { _cursor_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSetQualityPreferenceMsg")]
  public partial class CSetQualityPreferenceMsg : global::ProtoBuf.IExtensible
  {
    public CSetQualityPreferenceMsg() {}
    
    private EStreamQualityPreference _quality;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EStreamQualityPreference quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSetMaximumResolutionMsg")]
  public partial class CSetMaximumResolutionMsg : global::ProtoBuf.IExtensible
  {
    public CSetMaximumResolutionMsg() {}
    
    private uint _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }
    private uint _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSetMaximumFramerateMsg")]
  public partial class CSetMaximumFramerateMsg : global::ProtoBuf.IExtensible
  {
    public CSetMaximumFramerateMsg() {}
    
    private uint _framerate;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"framerate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint framerate
    {
      get { return _framerate; }
      set { _framerate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSetMaximumBitrateMsg")]
  public partial class CSetMaximumBitrateMsg : global::ProtoBuf.IExtensible
  {
    public CSetMaximumBitrateMsg() {}
    
    private int _bitrate;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bitrate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bitrate
    {
      get { return _bitrate; }
      set { _bitrate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSetQoSMsg")]
  public partial class CSetQoSMsg : global::ProtoBuf.IExtensible
  {
    public CSetQoSMsg() {}
    
    private bool _use_qos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"use_qos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool use_qos
    {
      get { return _use_qos; }
      set { _use_qos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSetTargetFramerateMsg")]
  public partial class CSetTargetFramerateMsg : global::ProtoBuf.IExtensible
  {
    public CSetTargetFramerateMsg() {}
    
    private uint _framerate;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"framerate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint framerate
    {
      get { return _framerate; }
      set { _framerate = value; }
    }

    private uint _reasons = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reasons", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint reasons
    {
      get { return _reasons; }
      set { _reasons = value; }
    }

    private uint _framerate_numerator = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"framerate_numerator", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint framerate_numerator
    {
      get { return _framerate_numerator; }
      set { _framerate_numerator = value; }
    }

    private uint _framerate_denominator = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"framerate_denominator", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint framerate_denominator
    {
      get { return _framerate_denominator; }
      set { _framerate_denominator = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"COverlayEnabledMsg")]
  public partial class COverlayEnabledMsg : global::ProtoBuf.IExtensible
  {
    public COverlayEnabledMsg() {}
    
    private bool _enabled;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"enabled", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool enabled
    {
      get { return _enabled; }
      set { _enabled = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CInputControllerAttachedMsg")]
  public partial class CInputControllerAttachedMsg : global::ProtoBuf.IExtensible
  {
    public CInputControllerAttachedMsg() {}
    
    private int _controller_index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"controller_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int controller_index
    {
      get { return _controller_index; }
      set { _controller_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CInputControllerStateMsg")]
  public partial class CInputControllerStateMsg : global::ProtoBuf.IExtensible
  {
    public CInputControllerStateMsg() {}
    

    private uint _input_mark = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"input_mark", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint input_mark
    {
      get { return _input_mark; }
      set { _input_mark = value; }
    }
    private int _controller_index;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"controller_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int controller_index
    {
      get { return _controller_index; }
      set { _controller_index = value; }
    }

    private ulong _buttons = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"buttons", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong buttons
    {
      get { return _buttons; }
      set { _buttons = value; }
    }

    private int _left_pad_x = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"left_pad_x", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int left_pad_x
    {
      get { return _left_pad_x; }
      set { _left_pad_x = value; }
    }

    private int _left_pad_y = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"left_pad_y", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int left_pad_y
    {
      get { return _left_pad_y; }
      set { _left_pad_y = value; }
    }

    private int _right_pad_x = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"right_pad_x", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int right_pad_x
    {
      get { return _right_pad_x; }
      set { _right_pad_x = value; }
    }

    private int _right_pad_y = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"right_pad_y", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int right_pad_y
    {
      get { return _right_pad_y; }
      set { _right_pad_y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTriggerHapticPulseMsg")]
  public partial class CTriggerHapticPulseMsg : global::ProtoBuf.IExtensible
  {
    public CTriggerHapticPulseMsg() {}
    
    private int _controller_index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"controller_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int controller_index
    {
      get { return _controller_index; }
      set { _controller_index = value; }
    }
    private int _pad_index;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pad_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pad_index
    {
      get { return _pad_index; }
      set { _pad_index = value; }
    }
    private uint _duration_microsec;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"duration_microsec", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint duration_microsec
    {
      get { return _duration_microsec; }
      set { _duration_microsec = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSetOverrideModeMsg")]
  public partial class CSetOverrideModeMsg : global::ProtoBuf.IExtensible
  {
    public CSetOverrideModeMsg() {}
    

    private int _window_type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"window_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int window_type
    {
      get { return _window_type; }
      set { _window_type = value; }
    }

    private string _override_mode = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"override_mode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string override_mode
    {
      get { return _override_mode; }
      set { _override_mode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CInputControllerDetachedMsg")]
  public partial class CInputControllerDetachedMsg : global::ProtoBuf.IExtensible
  {
    public CInputControllerDetachedMsg() {}
    
    private int _controller_index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"controller_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int controller_index
    {
      get { return _controller_index; }
      set { _controller_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CStreamDataLostMsg")]
  public partial class CStreamDataLostMsg : global::ProtoBuf.IExtensible
  {
    public CStreamDataLostMsg() {}
    
    private readonly global::System.Collections.Generic.List<uint> _packets = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"packets", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> packets
    {
      get { return _packets; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CAudioFormat")]
  public partial class CAudioFormat : global::ProtoBuf.IExtensible
  {
    public CAudioFormat() {}
    
    private EAudioFormat _format;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"format", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EAudioFormat format
    {
      get { return _format; }
      set { _format = value; }
    }

    private uint _frequency = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"frequency", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint frequency
    {
      get { return _frequency; }
      set { _frequency = value; }
    }

    private uint _channels = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"channels", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint channels
    {
      get { return _channels; }
      set { _channels = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CVideoFormat")]
  public partial class CVideoFormat : global::ProtoBuf.IExtensible
  {
    public CVideoFormat() {}
    
    private EVideoFormat _format;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"format", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EVideoFormat format
    {
      get { return _format; }
      set { _format = value; }
    }

    private uint _width = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint width
    {
      get { return _width; }
      set { _width = value; }
    }

    private uint _height = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint height
    {
      get { return _height; }
      set { _height = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CFrameEvent")]
  public partial class CFrameEvent : global::ProtoBuf.IExtensible
  {
    public CFrameEvent() {}
    
    private EStreamFrameEvent _event_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"event_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EStreamFrameEvent event_id
    {
      get { return _event_id; }
      set { _event_id = value; }
    }
    private uint _timestamp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CFrameStats")]
  public partial class CFrameStats : global::ProtoBuf.IExtensible
  {
    public CFrameStats() {}
    
    private uint _frame_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"frame_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint frame_id
    {
      get { return _frame_id; }
      set { _frame_id = value; }
    }

    private uint _input_mark = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"input_mark", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint input_mark
    {
      get { return _input_mark; }
      set { _input_mark = value; }
    }
    private readonly global::System.Collections.Generic.List<CFrameEvent> _events = new global::System.Collections.Generic.List<CFrameEvent>();
    [global::ProtoBuf.ProtoMember(3, Name=@"events", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CFrameEvent> events
    {
      get { return _events; }
    }
  
    private EStreamFrameResult _result;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EStreamFrameResult result
    {
      get { return _result; }
      set { _result = value; }
    }

    private float _frame_start_delta = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"frame_start_delta", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float frame_start_delta
    {
      get { return _frame_start_delta; }
      set { _frame_start_delta = value; }
    }

    private float _frame_display_delta = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"frame_display_delta", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float frame_display_delta
    {
      get { return _frame_display_delta; }
      set { _frame_display_delta = value; }
    }

    private float _ping_time = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ping_time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float ping_time
    {
      get { return _ping_time; }
      set { _ping_time = value; }
    }

    private float _server_bitrate = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"server_bitrate", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float server_bitrate
    {
      get { return _server_bitrate; }
      set { _server_bitrate = value; }
    }

    private float _client_bitrate = default(float);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"client_bitrate", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float client_bitrate
    {
      get { return _client_bitrate; }
      set { _client_bitrate = value; }
    }

    private float _link_bandwidth = default(float);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"link_bandwidth", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float link_bandwidth
    {
      get { return _link_bandwidth; }
      set { _link_bandwidth = value; }
    }

    private float _packet_loss = default(float);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"packet_loss", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float packet_loss
    {
      get { return _packet_loss; }
      set { _packet_loss = value; }
    }

    private uint _frame_size = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"frame_size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint frame_size
    {
      get { return _frame_size; }
      set { _frame_size = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CFrameStatAccumulatedValue")]
  public partial class CFrameStatAccumulatedValue : global::ProtoBuf.IExtensible
  {
    public CFrameStatAccumulatedValue() {}
    
    private EFrameAccumulatedStat _stat_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"stat_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EFrameAccumulatedStat stat_type
    {
      get { return _stat_type; }
      set { _stat_type = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private float _average;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"average", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float average
    {
      get { return _average; }
      set { _average = value; }
    }

    private float _stddev = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"stddev", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float stddev
    {
      get { return _stddev; }
      set { _stddev = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CFrameStatsListMsg")]
  public partial class CFrameStatsListMsg : global::ProtoBuf.IExtensible
  {
    public CFrameStatsListMsg() {}
    
    private EStreamingDataType _data_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"data_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EStreamingDataType data_type
    {
      get { return _data_type; }
      set { _data_type = value; }
    }
    private readonly global::System.Collections.Generic.List<CFrameStats> _stats = new global::System.Collections.Generic.List<CFrameStats>();
    [global::ProtoBuf.ProtoMember(2, Name=@"stats", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CFrameStats> stats
    {
      get { return _stats; }
    }
  
    private readonly global::System.Collections.Generic.List<CFrameStatAccumulatedValue> _accumulated_stats = new global::System.Collections.Generic.List<CFrameStatAccumulatedValue>();
    [global::ProtoBuf.ProtoMember(3, Name=@"accumulated_stats", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CFrameStatAccumulatedValue> accumulated_stats
    {
      get { return _accumulated_stats; }
    }
  
    private int _latest_frame_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"latest_frame_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int latest_frame_id
    {
      get { return _latest_frame_id; }
      set { _latest_frame_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CDebugDumpMsg")]
  public partial class CDebugDumpMsg : global::ProtoBuf.IExtensible
  {
    public CDebugDumpMsg() {}
    

    private byte[] _screenshot = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"screenshot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] screenshot
    {
      get { return _screenshot; }
      set { _screenshot = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EStreamChannel", EnumPassthru=true)]
    public enum EStreamChannel
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamChannelInvalid", Value=-1)]
      k_EStreamChannelInvalid = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamChannelDiscovery", Value=0)]
      k_EStreamChannelDiscovery = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamChannelControl", Value=1)]
      k_EStreamChannelControl = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamChannelStats", Value=2)]
      k_EStreamChannelStats = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamChannelDataChannelStart", Value=3)]
      k_EStreamChannelDataChannelStart = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EStreamDiscoveryMessage", EnumPassthru=true)]
    public enum EStreamDiscoveryMessage
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamDiscoveryRequest", Value=1)]
      k_EStreamDiscoveryRequest = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamDiscoveryResponse", Value=2)]
      k_EStreamDiscoveryResponse = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EStreamControlMessage", EnumPassthru=true)]
    public enum EStreamControlMessage
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlAuthenticationRequest", Value=1)]
      k_EStreamControlAuthenticationRequest = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlAuthenticationResponse", Value=2)]
      k_EStreamControlAuthenticationResponse = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlNegotiationInit", Value=3)]
      k_EStreamControlNegotiationInit = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlNegotiationSetConfig", Value=4)]
      k_EStreamControlNegotiationSetConfig = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlNegotiationComplete", Value=5)]
      k_EStreamControlNegotiationComplete = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControl_LAST_SETUP_MESSAGE", Value=15)]
      k_EStreamControl_LAST_SETUP_MESSAGE = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlStartAudioData", Value=50)]
      k_EStreamControlStartAudioData = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlStopAudioData", Value=51)]
      k_EStreamControlStopAudioData = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlStartVideoData", Value=52)]
      k_EStreamControlStartVideoData = 52,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlStopVideoData", Value=53)]
      k_EStreamControlStopVideoData = 53,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlInputMouseMotion", Value=54)]
      k_EStreamControlInputMouseMotion = 54,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlInputMouseWheel", Value=55)]
      k_EStreamControlInputMouseWheel = 55,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlInputMouseDown", Value=56)]
      k_EStreamControlInputMouseDown = 56,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlInputMouseUp", Value=57)]
      k_EStreamControlInputMouseUp = 57,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlInputKeyDown", Value=58)]
      k_EStreamControlInputKeyDown = 58,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlInputKeyUp", Value=59)]
      k_EStreamControlInputKeyUp = 59,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlInputGamepadAttached", Value=60)]
      k_EStreamControlInputGamepadAttached = 60,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlInputGamepadEvent", Value=61)]
      k_EStreamControlInputGamepadEvent = 61,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlInputGamepadDetached", Value=62)]
      k_EStreamControlInputGamepadDetached = 62,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlShowCursor", Value=63)]
      k_EStreamControlShowCursor = 63,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlHideCursor", Value=64)]
      k_EStreamControlHideCursor = 64,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlSetCursor", Value=65)]
      k_EStreamControlSetCursor = 65,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlGetCursorImage", Value=66)]
      k_EStreamControlGetCursorImage = 66,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlSetCursorImage", Value=67)]
      k_EStreamControlSetCursorImage = 67,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlDeleteCursor", Value=68)]
      k_EStreamControlDeleteCursor = 68,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlSetTargetFramerate", Value=69)]
      k_EStreamControlSetTargetFramerate = 69,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlInputLatencyTest", Value=70)]
      k_EStreamControlInputLatencyTest = 70,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlGamepadRumble", Value=71)]
      k_EStreamControlGamepadRumble = 71,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlSetMaximumFramerate", Value=72)]
      k_EStreamControlSetMaximumFramerate = 72,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlSetMaximumBitrate", Value=73)]
      k_EStreamControlSetMaximumBitrate = 73,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlOverlayEnabled", Value=74)]
      k_EStreamControlOverlayEnabled = 74,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlInputControllerAttached", Value=75)]
      k_EStreamControlInputControllerAttached = 75,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlInputControllerState", Value=76)]
      k_EStreamControlInputControllerState = 76,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlTriggerHapticPulse", Value=77)]
      k_EStreamControlTriggerHapticPulse = 77,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlInputControllerDetached", Value=78)]
      k_EStreamControlInputControllerDetached = 78,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlSystemInfo", Value=79)]
      k_EStreamControlSystemInfo = 79,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlVideoDecoderInfo", Value=80)]
      k_EStreamControlVideoDecoderInfo = 80,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlSetTitle", Value=81)]
      k_EStreamControlSetTitle = 81,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlSetIcon", Value=82)]
      k_EStreamControlSetIcon = 82,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlQuitRequest", Value=83)]
      k_EStreamControlQuitRequest = 83,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlSetOverrideMode", Value=84)]
      k_EStreamControlSetOverrideMode = 84,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlSetMaximumResolution", Value=85)]
      k_EStreamControlSetMaximumResolution = 85,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlSetQualityPreference", Value=86)]
      k_EStreamControlSetQualityPreference = 86,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamControlSetQoS", Value=87)]
      k_EStreamControlSetQoS = 87
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EStreamVersion", EnumPassthru=true)]
    public enum EStreamVersion
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamVersionNone", Value=0)]
      k_EStreamVersionNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamVersionCurrent", Value=1)]
      k_EStreamVersionCurrent = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EStreamAudioCodec", EnumPassthru=true)]
    public enum EStreamAudioCodec
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamAudioCodecNone", Value=0)]
      k_EStreamAudioCodecNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamAudioCodecRaw", Value=1)]
      k_EStreamAudioCodecRaw = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamAudioCodecVorbis", Value=2)]
      k_EStreamAudioCodecVorbis = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamAudioCodecOpus", Value=3)]
      k_EStreamAudioCodecOpus = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamAudioCodecMP3", Value=4)]
      k_EStreamAudioCodecMP3 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamAudioCodecAAC", Value=5)]
      k_EStreamAudioCodecAAC = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EStreamVideoCodec", EnumPassthru=true)]
    public enum EStreamVideoCodec
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamVideoCodecNone", Value=0)]
      k_EStreamVideoCodecNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamVideoCodecRaw", Value=1)]
      k_EStreamVideoCodecRaw = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamVideoCodecVP8", Value=2)]
      k_EStreamVideoCodecVP8 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamVideoCodecVP9", Value=3)]
      k_EStreamVideoCodecVP9 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamVideoCodecH264", Value=4)]
      k_EStreamVideoCodecH264 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamVideoCodecH265", Value=5)]
      k_EStreamVideoCodecH265 = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamVideoCodecORBX1", Value=6)]
      k_EStreamVideoCodecORBX1 = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamVideoCodecORBX2", Value=7)]
      k_EStreamVideoCodecORBX2 = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EStreamingDataType", EnumPassthru=true)]
    public enum EStreamingDataType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamingAudioData", Value=0)]
      k_EStreamingAudioData = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamingVideoData", Value=1)]
      k_EStreamingVideoData = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EStreamMouseButton", EnumPassthru=true)]
    public enum EStreamMouseButton
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamMouseButtonLeft", Value=1)]
      k_EStreamMouseButtonLeft = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamMouseButtonRight", Value=2)]
      k_EStreamMouseButtonRight = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamMouseButtonMiddle", Value=16)]
      k_EStreamMouseButtonMiddle = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamMouseButtonX1", Value=32)]
      k_EStreamMouseButtonX1 = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamMouseButtonX2", Value=64)]
      k_EStreamMouseButtonX2 = 64,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamMouseButtonUnknown", Value=4096)]
      k_EStreamMouseButtonUnknown = 4096
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EStreamMouseWheelDirection", EnumPassthru=true)]
    public enum EStreamMouseWheelDirection
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamMouseWheelUp", Value=120)]
      k_EStreamMouseWheelUp = 120,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamMouseWheelDown", Value=-120)]
      k_EStreamMouseWheelDown = -120
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EStreamGamepadInputType", EnumPassthru=true)]
    public enum EStreamGamepadInputType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputInvalid", Value=0)]
      k_EStreamGamepadInputInvalid = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputDPadUp", Value=1)]
      k_EStreamGamepadInputDPadUp = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputDPadDown", Value=2)]
      k_EStreamGamepadInputDPadDown = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputDPadLeft", Value=4)]
      k_EStreamGamepadInputDPadLeft = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputDPadRight", Value=8)]
      k_EStreamGamepadInputDPadRight = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputStart", Value=16)]
      k_EStreamGamepadInputStart = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputBack", Value=32)]
      k_EStreamGamepadInputBack = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputLeftThumb", Value=64)]
      k_EStreamGamepadInputLeftThumb = 64,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputRightThumb", Value=128)]
      k_EStreamGamepadInputRightThumb = 128,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputLeftShoulder", Value=256)]
      k_EStreamGamepadInputLeftShoulder = 256,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputRightShoulder", Value=512)]
      k_EStreamGamepadInputRightShoulder = 512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputGuide", Value=1024)]
      k_EStreamGamepadInputGuide = 1024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputA", Value=4096)]
      k_EStreamGamepadInputA = 4096,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputB", Value=8192)]
      k_EStreamGamepadInputB = 8192,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputX", Value=16384)]
      k_EStreamGamepadInputX = 16384,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputY", Value=32768)]
      k_EStreamGamepadInputY = 32768,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputLeftThumbX", Value=65536)]
      k_EStreamGamepadInputLeftThumbX = 65536,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputLeftThumbY", Value=131072)]
      k_EStreamGamepadInputLeftThumbY = 131072,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputRightThumbX", Value=262144)]
      k_EStreamGamepadInputRightThumbX = 262144,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputRightThumbY", Value=524288)]
      k_EStreamGamepadInputRightThumbY = 524288,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputLeftTrigger", Value=1048576)]
      k_EStreamGamepadInputLeftTrigger = 1048576,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamGamepadInputRightTrigger", Value=2097152)]
      k_EStreamGamepadInputRightTrigger = 2097152
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EStreamQualityPreference", EnumPassthru=true)]
    public enum EStreamQualityPreference
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamQualityFast", Value=1)]
      k_EStreamQualityFast = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamQualityBalanced", Value=2)]
      k_EStreamQualityBalanced = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamQualityBeautiful", Value=3)]
      k_EStreamQualityBeautiful = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EStreamBitrate", EnumPassthru=true)]
    public enum EStreamBitrate
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamBitrateAutodetect", Value=-1)]
      k_EStreamBitrateAutodetect = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamBitrateUnlimited", Value=0)]
      k_EStreamBitrateUnlimited = 0
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EStreamFramerateLimiter", EnumPassthru=true)]
    public enum EStreamFramerateLimiter
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFramerateSlowCapture", Value=1)]
      k_EStreamFramerateSlowCapture = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFramerateSlowConvert", Value=2)]
      k_EStreamFramerateSlowConvert = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFramerateSlowEncode", Value=4)]
      k_EStreamFramerateSlowEncode = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFramerateSlowNetwork", Value=8)]
      k_EStreamFramerateSlowNetwork = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFramerateSlowDecode", Value=16)]
      k_EStreamFramerateSlowDecode = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFramerateSlowGame", Value=32)]
      k_EStreamFramerateSlowGame = 32
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EStreamDataMessage", EnumPassthru=true)]
    public enum EStreamDataMessage
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamDataPacket", Value=1)]
      k_EStreamDataPacket = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamDataLost", Value=2)]
      k_EStreamDataLost = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EAudioFormat", EnumPassthru=true)]
    public enum EAudioFormat
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EAudioFormatNone", Value=0)]
      k_EAudioFormatNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EAudioFormat16BitLittleEndian", Value=1)]
      k_EAudioFormat16BitLittleEndian = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EAudioFormatFloat", Value=2)]
      k_EAudioFormatFloat = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EVideoFormat", EnumPassthru=true)]
    public enum EVideoFormat
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EVideoFormatNone", Value=0)]
      k_EVideoFormatNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EVideoFormatYV12", Value=1)]
      k_EVideoFormatYV12 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EVideoFormatAccel", Value=2)]
      k_EVideoFormatAccel = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EStreamStatsMessage", EnumPassthru=true)]
    public enum EStreamStatsMessage
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamStatsFrameEvents", Value=1)]
      k_EStreamStatsFrameEvents = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamStatsDebugDump", Value=2)]
      k_EStreamStatsDebugDump = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EStreamFrameEvent", EnumPassthru=true)]
    public enum EStreamFrameEvent
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamInputEventStart", Value=0)]
      k_EStreamInputEventStart = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamInputEventSend", Value=1)]
      k_EStreamInputEventSend = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamInputEventRecv", Value=2)]
      k_EStreamInputEventRecv = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamInputEventQueued", Value=3)]
      k_EStreamInputEventQueued = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamInputEventHandled", Value=4)]
      k_EStreamInputEventHandled = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameEventStart", Value=5)]
      k_EStreamFrameEventStart = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameEventCaptureBegin", Value=6)]
      k_EStreamFrameEventCaptureBegin = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameEventCaptureEnd", Value=7)]
      k_EStreamFrameEventCaptureEnd = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameEventConvertBegin", Value=8)]
      k_EStreamFrameEventConvertBegin = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameEventConvertEnd", Value=9)]
      k_EStreamFrameEventConvertEnd = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameEventEncodeBegin", Value=10)]
      k_EStreamFrameEventEncodeBegin = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameEventEncodeEnd", Value=11)]
      k_EStreamFrameEventEncodeEnd = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameEventSend", Value=12)]
      k_EStreamFrameEventSend = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameEventRecv", Value=13)]
      k_EStreamFrameEventRecv = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameEventDecodeBegin", Value=14)]
      k_EStreamFrameEventDecodeBegin = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameEventDecodeEnd", Value=15)]
      k_EStreamFrameEventDecodeEnd = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameEventUploadBegin", Value=16)]
      k_EStreamFrameEventUploadBegin = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameEventUploadEnd", Value=17)]
      k_EStreamFrameEventUploadEnd = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameEventComplete", Value=18)]
      k_EStreamFrameEventComplete = 18
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EStreamFrameResult", EnumPassthru=true)]
    public enum EStreamFrameResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameResultPending", Value=0)]
      k_EStreamFrameResultPending = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameResultDisplayed", Value=1)]
      k_EStreamFrameResultDisplayed = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameResultDroppedNetworkSlow", Value=2)]
      k_EStreamFrameResultDroppedNetworkSlow = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameResultDroppedNetworkLost", Value=3)]
      k_EStreamFrameResultDroppedNetworkLost = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameResultDroppedDecodeSlow", Value=4)]
      k_EStreamFrameResultDroppedDecodeSlow = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameResultDroppedDecodeCorrupt", Value=5)]
      k_EStreamFrameResultDroppedDecodeCorrupt = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameResultDroppedLate", Value=6)]
      k_EStreamFrameResultDroppedLate = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EStreamFrameResultDroppedReset", Value=7)]
      k_EStreamFrameResultDroppedReset = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EFrameAccumulatedStat", EnumPassthru=true)]
    public enum EFrameAccumulatedStat
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EFrameStatFPS", Value=0)]
      k_EFrameStatFPS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EFrameStatCaptureDurationMS", Value=1)]
      k_EFrameStatCaptureDurationMS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EFrameStatConvertDurationMS", Value=2)]
      k_EFrameStatConvertDurationMS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EFrameStatEncodeDurationMS", Value=3)]
      k_EFrameStatEncodeDurationMS = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EFrameStatSteamDurationMS", Value=4)]
      k_EFrameStatSteamDurationMS = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EFrameStatServerDurationMS", Value=5)]
      k_EFrameStatServerDurationMS = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EFrameStatNetworkDurationMS", Value=6)]
      k_EFrameStatNetworkDurationMS = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EFrameStatDecodeDurationMS", Value=7)]
      k_EFrameStatDecodeDurationMS = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EFrameStatDisplayDurationMS", Value=8)]
      k_EFrameStatDisplayDurationMS = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EFrameStatClientDurationMS", Value=9)]
      k_EFrameStatClientDurationMS = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EFrameStatFrameDurationMS", Value=10)]
      k_EFrameStatFrameDurationMS = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EFrameStatInputLatencyMS", Value=11)]
      k_EFrameStatInputLatencyMS = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EFrameStatGameLatencyMS", Value=12)]
      k_EFrameStatGameLatencyMS = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EFrameStatRoundTripLatencyMS", Value=13)]
      k_EFrameStatRoundTripLatencyMS = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EFrameStatPingTimeMS", Value=14)]
      k_EFrameStatPingTimeMS = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EFrameStatServerBitrateKbitPerSec", Value=15)]
      k_EFrameStatServerBitrateKbitPerSec = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EFrameStatClientBitrateKbitPerSec", Value=16)]
      k_EFrameStatClientBitrateKbitPerSec = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EFrameStatLinkBandwidthKbitPerSec", Value=17)]
      k_EFrameStatLinkBandwidthKbitPerSec = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"k_EFrameStatPacketLossPercentage", Value=18)]
      k_EFrameStatPacketLossPercentage = 18
    }
  
}
#pragma warning restore 1591
